env:
  browser: true
  es2021: true
extends: love
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  '@typescript-eslint/prefer-nullish-coalescing': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'

